name: techvision-frappe

x-image: &image
  image: ${CUSTOM_IMAGE:-ghcr.io/mehariwamlake/mail}:${CUSTOM_TAG:-latest}
  restart: unless-stopped

x-backend: &backend
  <<: *image
  volumes:
    - sites:/home/frappe/frappe-bench/sites

services:

  # -------------------------
  # DATABASE
  # -------------------------
  mariadb:
    image: mariadb:10.8
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    volumes:
      - mariadb-data:/var/lib/mysql

  # -------------------------
  # REDIS
  # -------------------------
  redis-cache:
    image: redis:7-alpine
    restart: unless-stopped

  redis-queue:
    image: redis:7-alpine
    restart: unless-stopped

  
  # -------------------------
  # BACKEND
  # -------------------------
  backend:
    <<: *backend
    depends_on:
      create-site:
        condition: service_completed_successfully

  # -------------------------
  # WEBSOCKET
  # -------------------------
  websocket:
    <<: *backend
    command: node /home/frappe/frappe-bench/apps/frappe/socketio.js
    depends_on:
      create-site:
        condition: service_completed_successfully
      redis-queue:
        condition: service_started

  # -------------------------
  # FRONTEND
  # -------------------------
  frontend:
    <<: *image
    command: ["nginx-entrypoint.sh"]
    environment:
      BACKEND: backend:8000
      SOCKETIO: websocket:9000
      FRAPPE_SITE_NAME_HEADER: mail.techvision.edu.et
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    depends_on:
      - backend
      - websocket

  # -------------------------
  # WORKERS
  # -------------------------
  queue-short:
    <<: *backend
    command: bench worker --queue short,default
    depends_on:
      create-site:
        condition: service_completed_successfully

  queue-long:
    <<: *backend
    command: bench worker --queue long,default,short
    depends_on:
      create-site:
        condition: service_completed_successfully

  scheduler:
    <<: *backend
    command: bench schedule
    depends_on:
      create-site:
        condition: service_completed_successfully

# -------------------------
# VOLUMES
# -------------------------
volumes:
  sites:
    driver: local
  mariadb-data: