ARG FRAPPE_BRANCH=version-16
ARG FRAPPE_IMAGE_PREFIX=frappe

# ----------------------------
# Builder
# ----------------------------
FROM ${FRAPPE_IMAGE_PREFIX}/build:${FRAPPE_BRANCH} AS builder

ARG FRAPPE_PATH=https://github.com/frappe/frappe

USER frappe

RUN --mount=type=secret,id=apps_json \
  set -euxo pipefail && \
  rm -rf /home/frappe/frappe-bench && \
  export NODE_OPTIONS="--max-old-space-size=2048" && \
  export YARN_ENABLE_IMMUTABLE_INSTALLS=false && \
  export APP_INSTALL_ARGS="" && \
  if [ -f /run/secrets/apps_json ] && [ -s /run/secrets/apps_json ]; then \
    mkdir -p /opt/frappe && \
    cp /run/secrets/apps_json /opt/frappe/apps.json && \
    echo "=== USING apps.json ===" && \
    cat /opt/frappe/apps.json && \
    APP_INSTALL_ARGS="--apps_path=/opt/frappe/apps.json"; \
  else \
    echo "=== NO apps.json PROVIDED ==="; \
  fi && \
  bench init ${APP_INSTALL_ARGS} \
    --frappe-branch=${FRAPPE_BRANCH} \
    --frappe-path=${FRAPPE_PATH} \
    --no-procfile \
    --no-backups \
    --skip-redis-config-generation \
    --verbose \
    /home/frappe/frappe-bench && \
  cd /home/frappe/frappe-bench && \
  echo "{}" > sites/common_site_config.json && \
  find apps -mindepth 1 -path "*/.git" -exec rm -rf {} +

# ----------------------------
# Runtime image
# ----------------------------
FROM ${FRAPPE_IMAGE_PREFIX}/base:${FRAPPE_BRANCH} AS backend

USER frappe

COPY --from=builder --chown=frappe:frappe /home/frappe/frappe-bench /home/frappe/frappe-bench

WORKDIR /home/frappe/frappe-bench

VOLUME [ \
  "/home/frappe/frappe-bench/sites", \
  "/home/frappe/frappe-bench/logs" \
]

CMD [ \
  "/home/frappe/frappe-bench/env/bin/gunicorn", \
  "--chdir=/home/frappe/frappe-bench/sites", \
  "--bind=0.0.0.0:8000", \
  "--threads=4", \
  "--workers=2", \
  "--worker-class=gthread", \
  "--worker-tmp-dir=/dev/shm", \
  "--timeout=120", \
  "--preload", \
  "frappe.app:application" \
]